### ISSUE TITLE
Relationship loss

### ISSUE THREAD

**Issue by artest08** [OpenDriveLab/TopoNet#10]
Hello,

Thank you for your nice study. Why are using (1-target) instead of directly the targets in the focal loss? I am having difficulty in understanding the concept behind that manipulation.  

https://github.com/OpenDriveLab/TopoNet/blob/b933f2817b02bdef4a47c90117dda3ba9544755a/projects/toponet/models/dense_heads/relationship_head.py#L100

Thanks in advance

**Comment by sephyli** [comment]
Hi, thanks for the good questuon.

In TopoNet, we utilize `focal loss` for relationship loss, proposed to address the imbalance between foreground and background predictions in object detection.
Our implementation employs the built-in version of `focal loss` from `mmdet`, available [here](https://github.com/open-mmlab/mmdetection/blob/v2.26.0/mmdet/models/losses/focal_loss.py). In the detection loss calculation, a ground truth class value of `0` indicates the foreground, while `1` refers the background. However, in our the ground truth of adjacent matrix, `1` denotes a positive connection. So the `1 - target` operation is utilized for this gap. 

Empirically, the gap come from the implement convenience of detection loss and classification loss. If you replace the `focal loss` to the `cross entropy loss`, this operation is not need.

A related and detailed discussion can be also found in the OpenLane-V2 repo issue [#17](https://github.com/OpenDriveLab/OpenLane-V2/issues/17).

**Comment by artest08** [comment]
Thank you so much. It is an excellent explanation. However, it is weird that mmdet library has implemented in that way :)
