### ISSUE TITLE
data_dict_subset_A_train.pkl missing

### ISSUE THREAD

**Issue by BertramLXH** [OpenDriveLab/TopoNet#14]
Thank you for your work. Here I have a little question that I follow the command to process dataset using "python OpenLane-V2/preprocess.py", but I don't get the .pkl file(eg. data_dict_subset_A_train.pkl), what's wrong? How can I get the .pkl file?

**Comment by sephyli** [comment]
You need to follow [OpenLane-V2](https://github.com/OpenDriveLab/OpenLane-V2/tree/v1.1.0/data) repo. First clone the OpenLane-V2 and then prepare dataset. Make ture the `data/OpenLane-V2/data_dict_subset_A.json` file is exsiting, then use  "python OpenLane-V2/preprocess.py" to get the .pkl file.

**Comment by BertramLXH** [comment]
That's worked! Thank you very much!
