### ISSUE TITLE
how to reduce batch size

### ISSUE THREAD

**Issue by BertramLXH** [OpenDriveLab/TopoNet#15]
Thank you for your awesome work! Here I have a little question that I met error: "RuntimeError: CUDA out of memory. Tried to allocate 2.40 GiB (GPU 6; 23.70 GiB total capacity; 20.97 GiB already allocated; 598.81 MiB free; 21.46 GiB reserved in total by PyTorch)". I think reducing the batch size can solve it. But I can't find the corresponding code to modify. Could you help me? 

Best regard!

**Comment by sephyli** [comment]
Hi, the batch size is default by 1 so you may cannot reduce it further. You can try (1) enable the checkpoint during training, (2) enable fp16, (3) reduce the image resize factor.

**Comment by BertramLXH** [comment]
> Hi, the batch size is default by 1 so you may cannot reduce it further. You can try (1) enable the checkpoint during training, (2) enable fp16, (3) reduce the image resize factor.

thank you for your answer~
