### ISSUE TITLE
Regression in box head is used twice. 

### ISSUE THREAD

**Issue by wenjie710** [OpenDriveLab/TopoNet#16]
Thanks for sharing the code ! 
Within the `box_head` section, the box refinement process has already been executed within the `self.transformer`. Consequently, the output inter_reference represents the combined result of the regression outcomes and the position of the reference points. Nevertheless, it appears that you have reapplied the refinement operation on the `inter_references` output. Is this a deliberate design choice or merely a minor oversight that does not significantly impact performance?

**Comment by wenjie710** [comment]
The` LC Head` appears to be implemented correctly, but the concern arises regarding the `TE head`. Given that we have set `with_box_refine=True`, the refinement process is indeed carried out within [`self.transformer`](https://github.com/OpenDriveLab/TopoNet/blob/827927b826ac6ed89237755846a1a44f39e621aa/projects/toponet/models/dense_heads/deformable_detr_head.py#L150). This ensures that the reference points undergo refinement at each layer. However, it seems that there is an additional redundant [refinement](https://github.com/OpenDriveLab/TopoNet/blob/827927b826ac6ed89237755846a1a44f39e621aa/projects/toponet/models/dense_heads/deformable_detr_head.py#L171) step applied to the output reference points.

**Comment by sephyli** [comment]
I see. We are currently utilizing the raw implementation of mmdet. 
Upon carefully reviewing the code, I discovered that the refinement process relies on the reference points from the last layer. To clarify, the first layer uses the `init_reference` points, while the second layer uses `inter_references[0]`, which corresponds to the `init_reference` refined with `reg_results[0]`.
Although this implementation may appear slightly misleading and redundant, it is indeed correct.

**Comment by wenjie710** [comment]
OK I see. Thank you for explaining it so clearly.
