### ISSUE TITLE
export onnx error ( We don't have an op for aten::mul but it isn't a special case )

### ISSUE THREAD

**Issue by reskipper** [OpenDriveLab/TopoNet#17]
when i export toponet to onnx ，report error as below :
RuntimeError: 0INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::mul but it isn't a special case. Argument types: Tensor, bool,

Any suggestions on how I can solve this problem? Thanks a lot.

**Comment by sephyli** [comment]
Thanks for your question. You may can upgrade your PyTorch version to fix this. The repository's dependency is flexible.

**Comment by reskipper** [comment]
I tried torch 1.13.0+cu116 and mmcv-full 1.7.0, but the error persists. If I upgrade the torch version further, the mmcv-full version compatible with it may not be suitable for mmdet.
If there are specific recommended versions, please let me know. Thanks!!

**Comment by sephyli** [comment]
I have a combination with torch 2.0 with CUDA 11.7/11.8, feel free to try.
I think torch 1.13 can also compatible with mmcv-full 1.6.0. You can directly try on 1.13.

```
torch==2.0
torchvision==0.15.0
mmcls==0.25.0
mmcv-full==1.6.0
mmdet==2.26.0
mmdet3d==1.0.0rc6
mmsegmentation==0.29.1
```

**Comment by reskipper** [comment]
Thank you for your suggestion. I've tried it, but it still doesn't work.
In fact, I encountered this error while exporting onnx for several repos. I will come back to provide further details if I find a solution.
