### ISSUE TITLE
How to save all test visualization results?

### ISSUE THREAD

**Issue by Andy20178** [OpenDriveLab/TopoNet#18]
Hello! TopoNet is a great job!  When I was running./tools/dist_test.sh 1 --show, I found that only a few visualizations of 10001, 10002, 10003 were saved, I was wondering how to save the visualizations of all the data?

**Comment by sephyli** [comment]
If you want to save every frame of the dataset, you could go to dataset's show function, set the show_num to a super large number, and modify the code about idx % x.
________________________________
发件人: Changsheng Lv ***@***.***>
发送时间: Sunday, April 28, 2024 9:56:12 PM
收件人: OpenDriveLab/TopoNet ***@***.***>
抄送: Subscribed ***@***.***>
主题: [OpenDriveLab/TopoNet] How to save all test visualization results? (Issue #18)


Hello! TopoNet is a great job! When I was running./tools/dist_test.sh 1 --show, I found that only a few visualizations of 10001, 10002, 10003 were saved, I was wondering how to save the visualizations of all the data?

―

**Comment by Andy20178** [comment]
I solved the problem, thank you!
