### ISSUE TITLE
Will you attend Openlanev2 Competition?

### ISSUE THREAD

**Issue by wudongming97** [OpenDriveLab/TopoNet#2]
Hi, 

This is great work from the Shanghai AI lab! But I see you release its results on the leaderboard.

Will you attend OpenLane Topology Competition?

**Comment by sephyli** [comment]
As there are organizers of this competition among the TopoNet author team, we will not be participating in the current challenge. The test result of TopoNet will serve only as another strong baseline to facilitate the community.

**Comment by wudongming97** [comment]
Okay! Thanks for your great work! 

I close the issue.
