### ISSUE TITLE
Inquire geo isolation dataset

### ISSUE THREAD

**Issue by hagianga21** [OpenDriveLab/TopoNet#3]
Hi, thanks for your work. Could you please share the geo isolation dataset you use in your paper at Table 1? (e.g. .json file, pkl, etc.) Thanks for your help!

**Comment by sephyli** [comment]
Hi, the OpenLane-V2 segment_id of the **_geo-isolation_** set is uploaded in [geo_isolation.txt](https://github.com/OpenDriveLab/TopoNet/files/12206152/geo_isolation.txt).

**Comment by hagianga21** [comment]
Thanks. That means you train the model with the training set as normal, and evaluate the model with the geo-isolation set?

**Comment by sephyli** [comment]
Yes.
