### ISSUE TITLE
The performance of traffice element

### ISSUE THREAD

**Issue by VijayLuo** [OpenDriveLab/TopoNet#5]
Thanks to you awesome work!  But when I training with repo code, the mAP of traffic elements is very low and the visualization result is wrong.

![image](https://github.com/OpenDriveLab/TopoNet/assets/24860958/9ace8897-c67e-4d0f-88cc-aa05189c7b1c)

`
2023-08-30 01:16:58,035 - mmdet - INFO - Epoch(val) [24][601]	OpenLane-V2 Score: 0.1291, DET_l: 0.2889845073223114, DET_t: 2.5147695851046592e-05, TOP_ll: 0.0411, TOP_lt: 0.0006
`

**Comment by sephyli** [comment]
Hi, @VijayLuo, I sincerely apologize for the mistake.
The bug came from the unscaled `gt_bboxes` and was caused by an incorrect order of the `train_pipeline` in the config. 
I have already fixed this issue. I kindly request you to retrain using the updated config.

**Comment by sephyli** [comment]
The fixed model and training log is uploaded. Please check the latest update.
