### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by ZhihaoWang1997** [OpenDriveLab/TopoNet#6]
Hello, thanks for the config and model you provided. I followed your tutorial for visualization, but I didn’t see the topological relationship between the lane centerline and traffic elements. I can see the topological relationship between lane centerlines normally

**Comment by sephyli** [comment]
The existing visualization code lacks the lcte relationship. I plan to incorporate it at a later stage. 
For now, you can make use of [`openlanev2.visualization.draw_annotation_pv(...)`](https://github.com/OpenDriveLab/OpenLane-V2/blob/v1.0.0/openlanev2/visualization/pv.py), but please note that it might require further development.

**Comment by sephyli** [comment]
I have uploaded the [code](https://github.com/OpenDriveLab/TopoNet/commit/ac2518c86e5a0aca5d35ba0f28aac851b99cba7a) for lcte relationship visualization.
Kindly update your repository to fetch the latest code and re-run.

<img src=https://github.com/OpenDriveLab/TopoNet/assets/39691156/65e51b76-6837-4dd6-8fa4-560c7d2e2dc4 width=60% />
