### ISSUE TITLE
about paper

### ISSUE THREAD

**Issue by eeeric1** [OpenDriveLab/TopoNet#8]
Hello, Thanks for your work, I have some questions about the paper.
In 4.1.2 Re-implementation of SOTA Method, you mentioned that "we supervise VectorMapNet and MapTR with centerline labels and use the element queries in their Transformer decoders as the instance queries to produce the driving scene topology." Want to know how it is done?
Looking forward to your reply!

**Comment by sephyli** [comment]
Hi, @eeeric1. Thank you for bringing this up. We apologize for any inconvenience caused.

Regarding the `centerline supervision`, we utilize polylines to represent centerline and feed the label to the VectorMapNet and MapTR. 
For VectorMapNet, the pre-processing of their approach is remained, e.g., generate keypoints (bounding box), simplify the polyline, and apply quantization to coordinates. (for their polyline generater). 
For MapTR, the centerline is interpolated at equidistant intervals to create 20 points, which serve as training label.

As for the `topology reasoning`, we first generate the instance queries of both approaches, based on their design in classification score prediction.
For VectorMapNet, we use the concatenate of 2 keypoint queries as the instance queries.
For MapTR, we calculate the average of the point queries to obtain the instance queries.
After that, a same topology head in TopoNet is applied to both of them to produce the driving scene topology.

**Comment by eeeric1** [comment]
Thanks for the reply!
Regarding topology reasoning for MapTR,  I first get the point queries,  calculate the average of the point queries, and send the average to the topology head. 
My result : The detection of lane lines and traffic lights are normal, but the topology(both lclc and lcte) score is very low. I don't know if I missed something.
